lib/glimesh_web/router.ex
defmodule GlimeshWeb.Router do
  use GlimeshWeb, :router

  import GlimeshWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {GlimeshWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug GlimeshWeb.Plugs.Floc
    plug GlimeshWeb.Plugs.Locale
    plug GlimeshWeb.Plugs.CfCountryPlug
    plug GlimeshWeb.Plugs.Ban
    plug GlimeshWeb.Plugs.UserAgent
    plug GlimeshWeb.UniqueUserPlug
    plug NavigationHistory.Tracker, excluded_paths: ["/users/log_in", "/users/register"]
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql_alpha_api do
    plug :accepts, ["json"]
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug :require_alpha_api_header
    plug GlimeshWeb.Plugs.ApiContextPlug
  end

  pipeline :graphql do
    plug :fetch_session
    plug :fetch_current_user
    plug :accepts, ["json"]
    plug GlimeshWeb.Plugs.OldApiContextPlug
  end

  pipeline :oauth do
    # This route does not use session / cookies, so CORS can be wide open
    plug GlimeshWeb.Plugs.Cors
    plug Plug.Parsers, parsers: [:urlendoded]
  end

  if Mix.env() in [:dev, :test] do
    scope "/" do
      pipe_through :browser

      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end

  scope "/api/oauth", GlimeshWeb do
    pipe_through :oauth

    post "/token", OauthController, :token
    post "/revoke", OauthController, :revoke
    post "/introspect", OauthController, :introspect
  end

  scope "/api/webhook", GlimeshWeb do
    pipe_through :api

    # post "/stripe", WebhookController, :stripe
    post "/taxidpro", WebhookController, :taxidpro
  end

  scope "/api/graph" do
    pipe_through :graphql_alpha_api

    forward "/", Glimesh.Api.GraphiQLPlug,
      schema: Glimesh.Api.Schema,
      socket: GlimeshWeb.GraphApiSocket,
      default_url: {__MODULE__, :graph_default_url},
      socket_url: {__MODULE__, :graph_socket_url},
      interface: :playground,
      analyze_complexity: true,
      max_complexity: 500
  end

  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug.GraphiQL,
      schema: Glimesh.OldSchema,
      socket: GlimeshWeb.OldApiSocket,
      default_url: {__MODULE__, :graphiql_default_url},
      socket_url: {__MODULE__, :graphiql_socket_url}
  end

  ## Authentication routes
  scope "/", GlimeshWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    post "/users/log_in_tfa", UserSessionController, :tfa
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings/takeout", TakeoutController, :index
    post "/users/settings/takeout", TakeoutController, :download

    post "/about/privacy", AboutController, :accept_privacy

    live "/platform_subscriptions", PlatformSubscriptionLive.Index, :index

    get "/users/social/twitter", UserSocialController, :twitter
    get "/users/social/twitter/connect", UserSocialController, :twitter_connect
    delete "/users/social/disconnect/:platform", UserSocialController, :disconnect

    get "/users/payments", UserPaymentsController, :index
    post "/users/payments/setup", UserPaymentsController, :setup
    get "/users/payments/taxes", UserPaymentsController, :taxes
    get "/users/payments/taxes_pending", UserPaymentsController, :taxes_pending
    get "/users/payments/connect", UserPaymentsController, :connect
    put "/users/payments/delete_default_payment", UserPaymentsController, :delete_default_payment

    get "/users/settings/profile", UserSettingsController, :profile
    get "/users/settings/stream", UserSettingsController, :stream

    get "/users/settings/channel_statistics", UserSettingsController, :channel_statistics
    get "/users/settings/addons", UserSettingsController, :addons
    get "/users/settings/emotes", UserSettingsController, :emotes
    get "/users/settings/upload_emotes", UserSettingsController, :upload_emotes
    get "/users/settings/hosting", UserSettingsController, :hosting

    put "/users/settings/create_channel", UserSettingsController, :create_channel
    put "/users/settings/delete_channel", UserSettingsController, :delete_channel
    get "/users/settings/preference", UserSettingsController, :preference
    put "/users/settings/preference", UserSettingsController, :update_preference
    put "/users/settings/update_profile", UserSettingsController, :update_profile
    put "/users/settings/update_channel", UserSettingsController, :update_channel
    get "/users/settings/notifications", UserSettingsController, :notifications

    get "/users/settings/security", UserSecurityController, :index
    put "/users/settings/update_password", UserSecurityController, :update_password
    put "/users/settings/update_email", UserSecurityController, :update_email
    get "/users/settings/confirm_email/:token", UserSecurityController, :confirm_email
    put "/users/settings/update_tfa", UserSecurityController, :update_tfa
    get "/users/settings/get_tfa", UserSecurityController, :get_tfa
    get "/users/settings/tfa_registered", UserSecurityController, :tfa_registered

    put "/users/settings/applications/:id/rotate", UserApplicationsController, :rotate
    resources "/users/settings/applications", UserApplicationsController

    resources "/users/settings/authorizations", UserAuthorizedAppsController,
      only: [:index, :delete],
      param: "id"

    get "/oauth/authorize", OauthController, :authorize
    post "/oauth/authorize", OauthController, :process_authorize
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_authenticated_user, :require_user_has_channel]

    post "/users/settings/channel/mods/ban_user",
         ChannelModeratorController,
         :ban_user

    delete "/users/settings/channel/mods/unban_user/:username",
           ChannelModeratorController,
           :unban_user

    resources "/users/settings/channel/mods", ChannelModeratorController
  end

  scope "/admin", GlimeshWeb do
    pipe_through [:browser, :require_admin_user]

    import Phoenix.LiveDashboard.Router

    live_dashboard "/phoenix/dashboard", metrics: GlimeshWeb.Telemetry, ecto_repos: [Glimesh.Repo]
  end

  scope "/gct", GlimeshWeb do
    pipe_through [:browser, :require_gct_user]

    get "/", GctController, :index
    get "/me", GctController, :edit_self
    get "/unauthorized", GctController, :unauthorized

    # Lookup scopes
    get "/lookup/user", GctController, :username_lookup
    get "/lookup/channel", GctController, :channel_lookup
    get "/lookup/channel/:channel_id/chat", GctController, :channel_chat_log
    get "/lookup/user/:user_id/chat", GctController, :user_chat_log

    # Editing profile scopes
    get "/edit/profile/:username", GctController, :edit_user_profile
    put "/edit/profile/:username/update", GctController, :update_user_profile

    # Editing user scopes
    get "/edit/:username", GctController, :edit_user
    put "/edit/:username/update", GctController, :update_user

    # Editing channel scopes
    get "/edit/channel/:channel_id", GctController, :edit_channel
    post "/edit/channel/:channel_id/shutdown", GctController, :shutdown_channel
    post "/edit/channel/:channel_id/bounce", GctController, :bounce_channel
    put "/edit/channel/:channel_id/update", GctController, :update_channel
    put "/edit/channel/:channel_id/delete", GctController, :delete_channel

    # Audit log
    get "/audit-log", GctController, :audit_log

    # Emote scopes
    get "/global-emotes", GctController, :global_emotes
    get "/review-emotes", GctController, :review_emotes

    # Categories and subcategories and tags and probably more
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser, :require_events_team_user]

    live "/events/admin", Events.EventsAdminLive, :index
  end

  scope "/", GlimeshWeb do
    pipe_through [:browser]

    get "/about", AboutController, :index
    get "/about/streaming", AboutController, :streaming
    get "/about/team", AboutController, :team
    get "/about/mission", AboutController, :mission
    get "/about/alpha", AboutController, :alpha
    get "/about/faq", AboutController, :faq
    get "/about/privacy", AboutController, :privacy
    get "/about/terms", AboutController, :terms
    get "/about/conduct", AboutController, :conduct
    get "/about/credits", AboutController, :credits
    get "/about/cookies", AboutController, :cookies
    get "/about/dmca", AboutController, :dmca

    live "/about/open-data", About.OpenDataLive, :index
    live "/about/open-data/subscriptions", About.OpenDataLive, :subscriptions
    live "/about/open-data/streams", About.OpenDataLive, :streams

    live "/about/app", About.AppLive, :index
    live "/about/go-live", About.GoLiveLive, :index

    live "/events", EventsLive, :index

    get "/blog", BlogMigrationController, :redirect_blog
    get "/blog/:slug", BlogMigrationController, :redirect_post

    live "/", HomepageLive, :index
    live "/streams", StreamsLive.Index, :index
    live "/streams/following", StreamsLive.Following, :index
    live "/streams/:category", StreamsLive.List, :index

    live "/users", UserLive.Index, :index

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new

lib/glimesh_web/live/about/app_live.ex
defmodule GlimeshWeb.About.AppLive do
  use GlimeshWeb, :live_view

  @impl true
  def render(assigns) do
    ~H"""
    <div class="container" style="max-width: 2200px; padding-left: 0; padding-right: 0;">
      <div style="background-color: #5271fd;">
        <div class="flex">
          <div class="col d-none d-md-flex align-items-center">
            <img class="img-fluid" src={~p"/images/about/app/app-demo.gif"} />
          </div>
          <div class="col d-flex flex-column justify-content-center">
            <h1 class="display-3 text-center m-4" style="font-family: Roboto;">The app is here!</h1>

            <p class="text-center lead mt-4">
              Finally, Glimesh from the comfort of your phone or tablet. Download it now!
            </p>

            <div class="row mx-4 mt-0 text-center">
              <div class="col-12 col-sm-6 px-4">
                <a href="https://apps.apple.com/us/app/glimesh/id1594860250" target="_blank">
                  <img class="img-fluid" src={~p"/images/about/app/download-on-the-app-store.png"} />
                </a>
              </div>
              <div class="col-12 col-sm-6 px-4">
                <a href="https://play.google.com/store/apps/details?id=tv.glimesh.app" target="_blank">
                  <img class="img-fluid" src={~p"/images/about/app/get-it-on-google-play.png"} />
                </a>
              </div>
            </div>
          </div>
        </div>

        <div class="flex">
          <div><img src={~p"/images/about/app/SC 1.jpg"} /></div>
          <div><img src={~p"/images/about/app/SC 2.jpg"} /></div>
          <div><img src={~p"/images/about/app/SC 3.jpg"} /></div>
          <div><img src={~p"/images/about/app/SC 4.jpg"} /></div>
          <div><img src={~p"/images/about/app/SC 5.jpg"} /></div>
          <div><img src={~p"/images/about/app/SC 6.jpg"} /></div>
        </div>
      </div>
    </div>
    """
  end

  @impl true
  def mount(_, session, socket) do
    if session["locale"], do: Gettext.put_locale(session["locale"])

    {:ok,
     socket
     |> assign(:page_title, "Mobile App")
     |> assign(:custom_meta, %{
       title: "Glimesh Mobile App",
       description:
         "The future of Glimesh is in your hands. Check out our new mobile app for iOS and Android!",
       image_url: url(~p"/images/about/app/app-social-preview.png"),
       card_type: "summary_large_image"
     })}
  end
end

lib/glimesh_web/live/about/open_data_live.ex
defmodule GlimeshWeb.About.OpenDataLive do
  use GlimeshWeb, :live_view

  @impl true
  def render(assigns) do
    ~H"""
    <div class="container mt-4">
      <h2><%= gettext("Open Data") %></h2>
      <p>
        <%= gettext(
          "Glimesh takes transparency to the exteme, as an open company we build in the public light, and we operate in the public light. We've built graphs for a couple common metrics we use, but if you have any questions about how we run, let us know!"
        ) %>
      </p>
      <div class="row mt-4">
        <div class="col-md-4">
          <div class="list-group">
            <%= live_redirect to: ~p"/about/open-data", class: "list-group-item list-group-item-action" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= gettext("Platform User Growth") %></h5>
              </div>
              <p class="mb-1">
                <%= gettext("Number of users on the platform over time, and net-new each week.") %>
              </p>
            <% end %>
            <%= live_redirect to: ~p"/about/open-data/subscriptions", class: "list-group-item list-group-item-action" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= gettext("Recurring Subscriptions") %></h5>
              </div>
              <p class="mb-1">
                <%= gettext("Channel subscriptions totals by month.") %>
              </p>
            <% end %>
            <%= live_redirect to: ~p"/about/open-data/streams", class: "list-group-item list-group-item-action" do %>
              <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= gettext("Live Streams") %></h5>
              </div>
              <p class="mb-1">
                <%= gettext("Number of unique streamers and peak viewers by week.") %>
              </p>
            <% end %>
          </div>
        </div>
        <div class="col-md-8">
          <div>
            <div
              id="open-data-line-chart"
              data-chart={@chart_data}
              phx-hook="LineChart"
              data-theme={@chart_theme}
            >
            </div>

            <p class="text-center"><%= gettext("Current week / month data updates daily.") %></p>
          </div>
        </div>
      </div>
    </div>
    """
  end

  @impl true
  def mount(_, session, socket) do
    if session["locale"], do: Gettext.put_locale(session["locale"])

    {:ok,
     socket
     |> assign(:chart_data, Jason.encode!(%{}))
     |> assign(:chart_theme, Map.get(session, "site_theme", "dark"))}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :index, _) do
    socket
    |> put_page_title(gettext("Platform User Growth"))
    |> assign(:chart_data, Glimesh.Charts.PlatformUserGrowth.json())
  end

  defp apply_action(socket, :subscriptions, _) do
    socket
    |> put_page_title(gettext("Recurring Subscriptions"))
    |> assign(:chart_data, Glimesh.Charts.RecurringSubscriptions.json())
  end

  defp apply_action(socket, :streams, _) do
    socket
    |> put_page_title(gettext("Live Streams"))
    |> assign(:chart_data, Glimesh.Charts.LiveStreams.json())
  end
end

lib/glimesh_web/live/channel/components/channel_title.ex
defmodule GlimeshWeb.Channel.Components.ChannelTitle do
  use GlimeshWeb, :component

  attr :channel, Glimesh.Streams.Channel, required: true

  def uneditable_title(assigns) do
    ~H"""
    <div>
      <h1 class="text-xl line-clamp-1"><%= @channel.title %></h1>
      <div class="space-x-1">
        <.link navigate={~p"/streams/#{@channel.category.slug}"} class="badge badge-primary">
          <%= @channel.category.name %>
        </.link>
        <%= if @channel.subcategory do %>
          <.link
            navigate={
              ~p"/streams/#{@channel.category.slug}?subcategory[]=#{@channel.subcategory.slug}"
            }
            class="badge badge-pill badge-info"
          >
            <%= @channel.subcategory.name %>
          </.link>
        <% end %>
        <%= for tag <- @channel.tags do %>
          <.link
            navigate={~p"/streams/#{@channel.category.slug}?tags[]=#{tag.slug}"}
            class="badge badge-pill"
          >
            <%= tag.name %>
          </.link>
        <% end %>
      </div>
    </div>
    """
  end
end

lib/glimesh_web/live/channel/components/live_player.ex
defmodule GlimeshWeb.Channel.Components.LivePlayer do
  use GlimeshWeb, :live_component

  attr :channel_id, :integer, required: true
  attr :janus_url, :string, default: ""
  attr :poster, :string, default: "/images/stream-not-started.jpg"
  attr :muted, :boolean, default: false
  attr :status, :string, default: "loading"

  def render(assigns) do
    ~H"""
    <video
      id={@id}
      class="h-full mx-auto"
      phx-hook="LivePlayer"
      controls
      playsinline
      poster={@poster}
      muted={@muted}
      data-janus-url={@janus_url}
      data-channel-id={@channel_id}
      data-status={@status}
    >
    </video>
    """
  end
end

lib/glimesh_web/live/streams_live/following.html.heex
<div class="container container-stream-list">
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
    <div class="col-md-12 mx-auto ">
      <h1 class="display-4 font-weight-normal">
        <%= gettext("Live Streams") %>
      </h1>
      <%= if length(@channels) == 0 do %>
        <p><%= gettext("None of the streams you follow are live.") %></p>
      <% end %>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <%= for channel <- @channels do %>
      <div class="col-sm-12 col-md-6 col-xl-4 mt-4">
        <%= link to: ~p"/#{channel.user.username}", class: "text-color-link" do %>
          <div class="card card-stream">
            <img
              src={
                Glimesh.StreamThumbnail.url({channel.stream.thumbnail, channel.stream}, :original)
              }
              alt={channel.title}
              class="card-img"
              height="468"
              width="832"
            />
            <div class="card-img-overlay h-100 d-flex flex-column justify-content-between">
              <div>
                <div class="card-stream-category">
                  <%= if channel.match_type == "hosting" do %>
                    <span class="badge badge-warning"><%= gettext("Hosted") %></span>
                  <% end %>
                </div>
                <div class="card-stream-tags">
                  <%= if channel.subcategory do %>
                    <span class="badge badge-info"><%= channel.subcategory.name %></span>
                  <% end %>
                  <%= for tag <- channel.tags do %>
                    <%= if tag.name == "Community Pride" do %>
                      <span class="badge text-dark bg-pride"><%= tag.name %></span>
                    <% else %>
                      <span class="badge badge-primary"><%= tag.name %></span>
                    <% end %>
                  <% end %>
                </div>
              </div>

              <div class="media card-stream-streamer">
                <img
                  src={Glimesh.Avatar.url({channel.user.avatar, channel.user}, :original)}
                  alt={channel.user.displayname}
                  width="48"
                  height="48"
                  class={[
                    "img-avatar mr-2",
                    if(Glimesh.Accounts.can_receive_payments?(channel.user),
                      do: "img-verified-streamer"
                    )
                  ]}
                />
                <div class="media-body">
                  <h6 class="mb-0 mt-1 card-stream-title"><%= channel.title %></h6>
                  <p class="mb-0 card-stream-username">
                    <%= channel.user.displayname %>
                    <span class="badge badge-info">
                      <%= Glimesh.Streams.get_channel_language(channel) %>
                    </span>
                    <%= if channel.mature_content do %>
                      <span class="badge badge-warning"><%= gettext("Mature") %></span>
                    <% end %>
                  </p>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center">
    <div class="col-md-12 mx-auto ">
      <h2 class="display-4 font-weight-normal">
        <%= gettext("All Followed Streamers") %>
      </h2>
      <%= if length(@users) == 0 do %>
        <p><%= gettext("You do not follow anyone who is offline.") %></p>
      <% end %>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <form phx-change="search">
        <div class="form-group mb-0">
          <input
            type="text"
            name="q"
            value={@query}
            placeholder={gettext("Search for usernames")}
            list="results"
            autocomplete="off"
            class="form-control form-control-lg"
          />
        </div>
      </form>
    </div>
  </div>
  <div
    id="users"
    class="row mt-2"
    phx-update={@update_mode}
    phx-hook="InfiniteScroll"
    data-page={@page}
  >
    <%= for user <- @users do %>
      <div id={"user-#{user.id}"} class="col-md-4 mb-4" phx-update="ignore">
        <%= live_component(GlimeshWeb.Components.UserCard, user: user) %>
      </div>
    <% end %>
  </div>
</div>

lib/glimesh_web/live/streams_live/video.html.leex
<div class="card">
  <div class="card-header p-1">
    <div class="row">
      <div class="col align-self-center d-block text-truncate">
        <%= live_render(@socket, GlimeshWeb.UserLive.Components.ChannelTitle, id: "channel-title", session: %{"user" => @user, "channel_id" => @channel.id}) %>
      </div>
      <div class="col-auto">
        <div class="float-right">
          <div class="stream-info btn-toolbar">
            <div class="btn-group mr-1" role="group" aria-label="First group">
              <%= if @can_receive_payments do %>
                <%= live_render(@socket, GlimeshWeb.UserLive.Components.SubscribeButton, id: "subscribe-button", session: %{"user" => @user, "streamer" => @streamer}) %>
              <% end %>
            </div>
            <div class="btn-group mr-1" role="group" aria-label="Second group">
              <%= live_render(@socket, GlimeshWeb.UserLive.Components.FollowButton, id: "follow-button", session: %{"user" => @user, "streamer" => @streamer}) %>
            </div>
            <div class="btn-group" role="group" aria-label="Third group">
              <%= live_render(@socket, GlimeshWeb.UserLive.Components.ViewerCount, id: "viewer-count", session: %{"channel_id" => @channel.id}) %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body p-0 p-md-1">
    <%= if @prompt_mature do %>
      <div class="jumbotron jumbotron-fluid jumbotron-mature-content mb-0">
        <div class="container p-5">
          <div class="row justify-content-center">
            <div class="col-sm-6">
              <h3 class="display-5 text-center"><%= gettext("Mature Content Warning") %></h3>
              <p class="lead text-center">
              <%= gettext("The streamer has flagged this channel as only appropriate for Mature Audiences.") %><br>
              <%= gettext("Do you wish to continue?") %>
              </p>
            </div>
            <div class="w-100"></div>
            <div class="col-8 col-lg-3">
              <button type="button" phx-click="show_mature" class="btn btn-primary btn-block"><%= gettext("Agree & View Channel") %></button>
            </div>
          </div>

        </div>
      </div>

    <% else %>
      <div id="video-container" class="embed-responsive embed-responsive-16by9">
        <video id="video-player" class="embed-responsive-item" phx-hook="FtlVideo" controls playsinline poster="<%= @channel_poster %>"></video>
        <div id="video-loading-container" class="">
          <div class="lds-ring">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="card-footer p-1 d-none d-sm-block">
    <div class="row">
      <div class="col-8 d-inline-flex align-items-center">
        <div id="streamer-avatar">
          <a href="<%= Routes.user_profile_path(@socket, :index, @channel.user.username) %>">
            <img src="<%= Glimesh.Avatar.url({@channel.user.avatar, @channel.user}, :original)%>" alt="<%= @channel.user.displayname %>" width="48" height="48" class="img-avatar mr-2 float-left <%= if Glimesh.Accounts.can_receive_payments?(@channel.user), do: "img-verified-streamer", else: "" %>">
          </a>
        </div>
        <a title="<%= gettext("View Profile") %>" class="<%= Glimesh.Chat.Effects.get_username_color(@channel.user) %>" href="<%= Routes.user_profile_path(@socket, :index, @channel.user.username) %>">
          <h3 class="mb-0"><%= @channel.user.displayname %></h3>
        </a>

        <span class="badge badge-pill badge-info ml-2"><%= Glimesh.Streams.get_channel_language(@channel) %></span>
        <%= if @channel.mature_content do %>
          <span class="badge badge-pill badge-warning ml-2"><%= gettext("Mature") %></span>
        <% end %>

        <%= live_render(@socket, GlimeshWeb.UserLive.Components.SocialButtons, id: "social-buttons", container: {:ul, class: "list-inline ml-2 mb-0"}, session: %{"user_id" => @streamer.id}) %>
      </div>
      <div class="col-4 align-self-center">
        <div class="float-right mr-sm-2">
          <div class="d-inline-block mr-sm-2">
            <a href="#" phx-click="toggle_debug" class="text-color-link <%= if @player_error, do: "text-warning", else: "" %>">
              <i class="fas fa-signal"></i>
              <span class="sr-only">Debug</span>
            </a>
          </div>
          <div class="d-inline-block">
            <%= live_render(@socket, GlimeshWeb.UserLive.Components.ReportButton, id: "report-button", session: %{"user" => @user, "streamer" => @streamer}) %>
          </div>
        </div>
      </div>
    </div>
    <%= if @show_debug do %>
      <div id="debugModal" class="live-modal" phx-capture-click="toggle_debug" phx-window-keydown="toggle_debug" phx-key="escape" phx-target="#debugModal" phx-page-loading>
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"><%= gettext("Debug Information") %></h5>
              <button type="button" class="close" phx-click="toggle_debug" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>

            <div class="modal-body">
              <%= if @player_error do %>
                <div class="alert alert-warning" role="alert">
                  <%= @player_error %>
                </div>
              <% end %>
              <pre class="px-2">
== Janus Edge Information ==
Edge Hostname: <%= @janus_hostname %>
Edge URL: <%= @janus_url %>
Reported Lost Packets: <%= @lost_packets %>
<br>
== Stream Metadata ==
# Stream Metadata no longer auto reloads,
# close & reopen modal to see newest data.
ingest_server: <%= @stream_metadata.ingest_server %>
ingest_viewers: <%= @stream_metadata.ingest_viewers %> // unused
stream_time_seconds: <%= @stream_metadata.stream_time_seconds %>

source_bitrate: <%= @stream_metadata.source_bitrate %>
source_ping: <%= @stream_metadata.source_ping %> // unused

recv_packets: <%= @stream_metadata.recv_packets %>
lost_packets: <%= @stream_metadata.lost_packets %> // unused
nack_packets: <%= @stream_metadata.nack_packets %> // unused

vendor_name: <%= @stream_metadata.vendor_name %>
vendor_version: <%= @stream_metadata.vendor_version %>

audio_codec: <%= @stream_metadata.audio_codec %>
video_codec: <%= @stream_metadata.video_codec %>
video_height: <%= @stream_metadata.video_height %> // unused
video_width: <%= @stream_metadata.video_width %> // unused

inserted_at: <%= @stream_metadata.inserted_at %>
updated_at: <%= @stream_metadata.updated_at %>
              </pre>
            </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>